// <auto-generated />
namespace AgencySystemDotNet.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class fix_issue : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fix_issue));
        
        string IMigrationMetadata.Id
        {
            get { return "202106031343476_fix_issue"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
